name: uruella_ai
description: Offline-first AI ecosystem with cyberpunk aesthetic

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.6.14
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.2.1
  file_picker: ^10.3.7 
  speech_to_text: ^7.3.0 
  permission_handler: ^11.3.0 
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  # flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.14.4



flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/templates/
    - assets/sounds/
    - assets/images/3dgraphics/
    - .env
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/static/Inter_18pt-Regular.ttf
        - asset: assets/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/static/Inter_18pt-Bold.ttf
          weight: 700


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/loga.jpg"

# flutter_native_splash:
#   # This creates the background color (matches your Flutter Splash)
#   color: "#FAFAFA" 
  
#   # Your logo file
#   image: assets/images/logo.png
  
#   # Branding (Optional - Android 12+)
#   branding: assets/images/logo.png
  
#   # Enforce full screen
#   fullscreen: true
  
#   # Android 12 specific (Background usually needs to be lighter or same)
#   android_12:
#     image: assets/images/logo.png
#     icon_background_color: "#FAFAFA"